name: Docker CI/CD Pipeline

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Tag Docker Image
      run: |
        docker pull my-dockerhub-user/my-app:latest || true
        docker build --cache-from=my-dockerhub-user/my-app:latest -t my-dockerhub-user/my-app:latest .
        docker tag my-dockerhub-user/my-app:latest my-dockerhub-user/my-app:${{ github.sha }}

    - name: Push Docker Image to Docker Hub
      run: |
        docker push my-dockerhub-user/my-app:latest
        docker push my-dockerhub-user/my-app:${{ github.sha }}
